### ISSUE TITLE
[Suggestion] Better documentation regarding color

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/PackMenu#10]
In the [existing wiki](https://github.com/Shadows-of-Fire/PackMenu/wiki/PackMenu-Button-Schema) it mentions a "converted hex color integer". I think this should be better explained as I spent 10-20 minutes trying to find out (and I still don't know) and had to edit the color value in the config by guessing.

If possible, I also think a more fully-featured wiki and documentation should be written that includes examples, instructions to change splash text, color explanations, etc.

**Comment by TKFRvisionOfficial** [comment]
Hey! I cant help you with your documentation problem but I figured the color problem out.

So what you want to do is figuring out what the hex value from your color is.
For example white is 0xffffff
Now you got to convert that to decimal (0xffffff --> 16777215)
Finally you got to define this as a string 
for example ``"fontColor": "16777215"``

Hope it helps bro...

**Comment by ghost** [comment]
Did you do that with just a hex to decimal converter? Because when I tried that it would never produce the right color ingame.

**Comment by TKFRvisionOfficial** [comment]
Yeah...nothing special
just typed "0xffffff in decimal" into google and used the google calculator...
![image](https://user-images.githubusercontent.com/52245132/82897101-5ed1cb80-9f57-11ea-8bf9-1b4979dff29b.png)
