### ISSUE TITLE
Crash on load of main menu

### ISSUE THREAD

**Issue by Sunekaer** [Shadows-of-Fire/PackMenu#11]
Crash log: https://paste.sunekaer.com/nikeceveja.rb
Config: https://paste.sunekaer.com/otopaqirek.bash
Minecraft Version: 1.15.2
Forge: 31.1.87

This crash doesn't happen every time

**Comment by Shadows-of-Fire** [comment]
That's a bit strange.  I'm not even sure if thats being caused by packmenu (the line in question is vanilla copypaste).

**Comment by Sunekaer** [comment]
Im not sure either what caused the crash, but this is just the only mod i see in the crash

**Comment by Shadows-of-Fire** [comment]
Closing this as I don't even know what's causing it, nor do I think there's anything I can do to fix it.
