### ISSUE TITLE
Question about custom gui screen.

### ISSUE THREAD

**Issue by Stanlyhalo** [Shadows-of-Fire/PackMenu#13]
I've been implementing this into my mod and I wanna ask, how do I make my own gui screen load? I see that in the ExtendedMenuScreen buttons like the Options Button opens up a new Screen gui that shows the options menu, but is it possible to load my own menu from a custom button? If so, how? Because these buttons in the java file load all the basic buttons, but their are already button json files for these buttons.

**Comment by Shadows-of-Fire** [comment]
You'd have to add a button in code to open a gui that is not already defined in ScreenType
