### ISSUE TITLE
Question on custom gui screens.

### ISSUE THREAD

**Issue by Stanlyhalo** [Shadows-of-Fire/PackMenu#14]
Hey, I'm back, is it possible atm with your files to change how the screen guis look, as in, if I make a copy of the OptionsScreen file and change the position of the basic buttons, can I change the textures of those buttons and the background? Right now, I'm trying to accomplish this, but I'm just asking the question if I can't find a solution myself.

**Comment by Shadows-of-Fire** [comment]
No, PM only allows for editing the main menu screen, the other screens are untouched, and the only way to edit those screens would be to change the global button/background textures.
