### ISSUE TITLE
Mark mod as clientside only

### ISSUE THREAD

**Issue by phit** [Shadows-of-Fire/PackMenu#15]
Please mark the mod as client only via
https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods

right now it will cause a red X in the server list if the mod is missing on the server, thanks!

**Comment by smmmadden** [comment]
may just be me, but I think you stated that backwards.  The subject says to mark the mod as client only, but the description says  if the mod is missing on the server (which it would be, if it were marked client only) there should NOT be a red x on the server list.  Unless of course the mod was placed on the server AND client I would expect the red x on the server list.

**Comment by phit** [comment]
its both ways, the name of the flag is kinda confusing 
as said in the docs
> Therefore, you should override the DISPLAYTEST extension point to make sure that Forge does not think your mod is required on the server

**Comment by smmmadden** [comment]
> its both ways, the name of the flag is kinda confusing
> as said in the docs
> 
> > Therefore, you should override the DISPLAYTEST extension point to make sure that Forge does not think your mod is required on the server

I couldn't find any reference to DISPLAYTEST extension point in the wiki, config files or on CurseForge for the mod.  Can you point me to where this is?

**Comment by phit** [comment]
nowhere? that's the whole issue, the link to the forge docs about it is in my first post..

**Comment by Shadows-of-Fire** [comment]
Closed as of 2.1.2
