### ISSUE TITLE
[Question] Doc for Slideshow Option

### ISSUE THREAD

**Issue by realTIMematrix** [Shadows-of-Fire/PackMenu#17]
Hi,

how can I use the slideshow option. Don't know what the format of the files is and in which path I should save this. Can you show some explanaiton?

    # How long between slideshow transitions. [range: 1 ~ 1000000, default: 200]
    I:Duration=200

    # The list of textures to be displayed on the slideshow.  If empty, the slideshow is ignored. [default: ]
    S:Textures <
     >

    # How long the slideshow transition lasts. [range: 1 ~ 1000000, default: 20]
    I:"Transition Duration"=20

What should be entered behind S:Textures? Do you have an example if the filename is slideshow_1.png etc

**Comment by Shadows-of-Fire** [comment]
Slideshow files must be provided in the resource pack and provided in resource location format.

That is, a file at `assets/packmenu/textures/slideshow/slide_1.png` would be represented in this config as `packmenu:textures/slideshow/slide_1.png`

**Comment by realTIMematrix** [comment]
It seems like this is not working. What I'm doing wrong here? The files are copied and i check the names. I've entered the following line:

`S:"Textures"=<packmenu:textures/slideshow/slideshow_0.png, packmenu:textures/slideshow/slideshow_1.png>
`

It doesn't work at all. I don't know how to enter multiple pictures and seperate them because the is no example how this can look like. Maybe you can write how the option should look like with 3 slideshow pictures?

**Comment by Shadows-of-Fire** [comment]
The format of the config spec is every entry is on a new line, with no data on the lines with the brackets.
as such,
```
S:"Textures" <
packmenu:textures/slideshow/slideshow_0.png
packmenu:textures/slideshow/slideshow_1.png
>
