### ISSUE TITLE
Panorama Support

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/PackMenu#2]
It would be really neat to be able to set the background as a custom panorama, much like Custom Main Menu allows.

I hope you'll consider it :)

**Comment by Shadows-of-Fire** [comment]
That is currently on the table as far as planning goes, just need to get there

**Comment by NielsPilgaard** [comment]
Awesome, thank you :)

**Comment by Shadows-of-Fire** [comment]
Actually, this should already be possible.  Just enable the vanilla panorama, and use the resource pack to override `minecraft:textures/gui/title/background/panorama_x` for [0-5].

**Comment by NielsPilgaard** [comment]
Oh, sweet, ty :D
