### ISSUE TITLE
The translation from language resourcepack is not be loaded when opens the game until clicking refresh.

### ISSUE THREAD

**Issue by CKFA** [Shadows-of-Fire/PackMenu#20]
As the title mentioned, everytime opens the game, the custom buttons do not recognise the lang key from the currently in use resourcepack which includes lang file, just shows the English instead of the custom language. Only working well, by pressing the reload button afterwards.

**Comment by fousaclp** [comment]
Hi.

I can also confirm this issue too.
Change of ingame language is OK.
But, only main menu stays in old language after change.  - need click to "reload" button.

BR,
Fousac
