### ISSUE TITLE
[Feature Request] Provide multiple panoramas, choose one at random when starting MC

### ISSUE THREAD

**Issue by Griefed** [Shadows-of-Fire/PackMenu#22]
Hey there Shadows-of-Fire,

if possible/feasible, I would love a feature where you could provide and define multiple panoramas for the main menu and when starting Minecraft, PackMenu picks one of them at random. 
I've encountered many beautiful worlds in my modpack, which highlight different areas/different content in it, so having a pool of panoramas for PackMenu to pick from could add to the esthetics of a modpack.

I would like to hear your thoughts on this.

Cheers,
Griefed

**Comment by Shadows-of-Fire** [comment]
Looking into this at present, it appears to be more difficult than a surface level would lead to believe because of the way panoramas are cached.

**Comment by Shadows-of-Fire** [comment]
Got it working, allows up to 10 possible variations of panorama, switched on startup or resource reload.

**Comment by Griefed** [comment]
Holy C, thank you so much!
