### ISSUE TITLE
[Feature Request] Allow opening of any Minecraft-recognizeable GUI

### ISSUE THREAD

**Issue by FireController1847** [Shadows-of-Fire/PackMenu#24]
Hi there,

I'd love for the ability to open up pretty much any of the primary GUIs using the "OPEN GUI" action. In particular, I'm looking to directly open the "Resource Packs..." screen from a custom button on the menu, but as a fellow modder I know there's tons of classes for various different GUIs which are able to be opened.

Would it be possible to add to the list of GUI menus a few of the other ones, such as ones inside of the options menu and such?

**Comment by Shadows-of-Fire** [comment]
You would have to request specific screens for this kinda feature request.

**Comment by FireController1847** [comment]
Yeah, sorry, I don't know what I was thinking then I suggested this. Can I recommend all of the buttons in the "Options" screen if possible to be opened? In particular I'm looking for "Resource Packs...", but it would be ideal if we could open any of the sub-menus in the options menu.

**Comment by Shadows-of-Fire** [comment]
Unfortunately that screen is weirdly bound to the options menu.  Best I can do is have it open it, but it will always go back to the options menu and not the main menu on exit

**Comment by Shadows-of-Fire** [comment]
Actually, even that's difficult, so it will probably be easier to just hack around to the original intended effect, since it needs hacking around to happen at all.

**Comment by Shadows-of-Fire** [comment]
Added under `RESOURCE_PACKS` data id for `OPEN_GUI`

**Comment by FireController1847** [comment]
Oh wow, thank you. I took a shot at a custom RESOURCE_PACKS screen and the only way I could get it to work was copying the code into the function passed. I may have to analyze your implementation to see how you did it haha
