### ISSUE TITLE
Really weird nether panorama shows up sometimes when my custom modpack is loaded. I have zero clue what is causing this, all my pack menu files seem like they are correct

### ISSUE THREAD

**Issue by JkubCC** [Shadows-of-Fire/PackMenu#27]
![2021-04-16_13 59 02](https://user-images.githubusercontent.com/82992682/115653728-b0b4da00-a2fd-11eb-97c8-ab8633037ad7.png)

**Comment by JkubCC** [comment]
![2021-04-22_00 03 50](https://user-images.githubusercontent.com/82992682/115654024-46506980-a2fe-11eb-9630-15c2464faed5.png)

This is what the menu is supposed to look like, there is also music aswell.
Id say about 50% of the time the bugged out panorama shows up

**Comment by ReeCodes** [comment]
SAME!

**Comment by BelgianDev** [comment]
Do you have maybe try to delete config? it can help

**Comment by Shadows-of-Fire** [comment]
That's the vanilla panorama.  I've never been able to reproduce it reliably, so I think it's some sort of race condition.

What I think happens is, based on mod loading times, sometimes this doesn't execute before the texture manager preloads all the panorama textures https://github.com/Shadows-of-Fire/PackMenu/blob/1.18/src/main/java/shadows/menu/PackMenuClient.java#L49

Might be able to fix it with a mixin

**Comment by Shadows-of-Fire** [comment]
Should... maybe be fixed 4.1.0 (1.18.2), if it still persists reopen this.
