### ISSUE TITLE
Fixing the Title images and Splash Text

### ISSUE THREAD

**Issue by SirPeteThe1st** [Shadows-of-Fire/PackMenu#31]
Is there any way to fix the png image of the title asset either by a specially created JSON file separate from buttons or by editing the graphic in an image editor so that it looks correct? Additionally, in which resource path would a custom splash text file go to replace the vanilla splash text file
![MM2](https://user-images.githubusercontent.com/70918592/135022608-38147207-9089-4041-8fc6-96c4dc22fca8.png)
?

**Comment by Shadows-of-Fire** [comment]
You just kinda have to edit the image to be in the file the way minecraft wants it to be, see the original one for reference on how big it is.
The location for slash texts is `minecraft:texts/splashes.txt`
