### ISSUE TITLE
An API for other mods to add stuff.

### ISSUE THREAD

**Issue by bradcarnage** [Shadows-of-Fire/PackMenu#36]
https://github.com/Sintinium/oauth/issues/11

**Comment by bradcarnage** [comment]
"After looking through their wiki and code PackMenu doesn't have an api for other mods. So until they add support there's not much I can do." - Sintinium

**Comment by Shadows-of-Fire** [comment]
I thought the relogin button was contained on the play menus, not the main menus.

In any case, its a screen, and forge has events to add buttons to arbitrary screens

**Comment by bradcarnage** [comment]
> its a screen, and forge has events to add buttons to arbitrary screens

How would I go about doing this?

**Comment by Shadows-of-Fire** [comment]
you can add buttons to any screen from the InitScreenEvent in a mod
