### ISSUE TITLE
Possibility of unification.

### ISSUE THREAD

**Issue by MrAkells** [Shadows-of-Fire/PackMenu#37]
I want to load all resources using kubejs, please add the ability to disable resource loader in packmenu.

**Comment by Shadows-of-Fire** [comment]
the builtin resource loader has no reason to be disabled, just don't include any files there.

**Comment by MrAkells** [comment]
If I provide a modpack for other players, do I need to create an empty PackMenu folder? This is silly. If I create a zip archive with only mods, configs, defaultconfigs, kubejs, then PackMenu will create the PackMenu folder again and overwrite my resources that I already loaded with KubeJS.
