### ISSUE TITLE
Logo with transparency levels doesn't render them transparent (1.16.5)

### ISSUE THREAD

**Issue by Asecave** [Shadows-of-Fire/PackMenu#38]
Each pixel of the logo eather is fully transparrent or fully solid with black background.
![Untitled](https://user-images.githubusercontent.com/39377667/155342461-20aa8f4f-cfd8-45ce-bd77-1a02b2cf136b.png)

**Comment by Asecave** [comment]
I see that you have fixed this in 1.18 and I understand it if you don't want to apply those fixes to older versions. So here is the point: I don't know how to build this project or rather I don't know how to fix these exceptions. I would fix this issue for the 1.16.5 version myself but I don't even come to this point. I do know Java.
Forge crashes in the early build process with a MethodNotFoundException or "invalid bare key: ${modid}". So it should be a problem with the Java version. I tried with Java 8 231 and Java 17. This is frustrating :(
[debug.log](https://github.com/Shadows-of-Fire/PackMenu/files/8146798/debug.log)
Edit: I fixed it with replacing all ${modid} with packmenu and using Java 8 271

**Comment by Shadows-of-Fire** [comment]
${modid}'s will be replaced on build, to ensure they exist to run in dev you just need to run `gradlew processResources` before first launch, and 1.16.5 does require java 8 (though I suppose you've figured that out).

Anyhow 1.16.5 is not supported, closing this.
