### ISSUE TITLE
Unable to locate the logo image

### ISSUE THREAD

**Issue by smmmadden** [Shadows-of-Fire/PackMenu#4]
With the CustomMainMenu I was able to replace the minecraft logo (top center text) from the splash background.  I'm not finding where in resources.zip has that logo or in the packmenu config file for the same.

Second, I'd like to put the text in the bottom left on separate rows, but /n and \n dont appear to be recognized as a new line.  Wiki page doesn't have all the details to help new users here.

**Comment by Shadows-of-Fire** [comment]
A) The logo image is part of vanilla, it is not re-shipped with packmenu, you should refer to the vanilla assets for vanilla resource paths.

B) Editing text is not supported, and is not currently planned.
