### ISSUE TITLE
Crash with modded when clicking singleplayer

### ISSUE THREAD

**Issue by Enterprise12nx01** [Shadows-of-Fire/PackMenu#41]
Some mods installed, when clicking singleplayer the client closes with a crash, not sure if related but Rubidium and Oculus are installed
Also OTG and its default world settings are applied(sets default dimension/worldgen settings for modpacks)

Debug.log: https://zerobin.net/?c86b596105f1addf#uczCWmRNrRk/k/MnAsy7k1zkbvcriYbQTAyrAEEzMAw=

**Comment by Shadows-of-Fire** [comment]
`at net.blay09.mods.defaultoptions.DefaultDifficultyHandler.onDrawScreen(DefaultDifficultyHandler.java:34)`
This crash is from default options, not PM
