### ISSUE TITLE
Slideshow has no transition

### ISSUE THREAD

**Issue by AlignedCookie88** [Shadows-of-Fire/PackMenu#43]
When my slideshow image changes, there is no transition. It just switches instantly. I have tried increasing the slideshow transition length value in the config.

**Comment by Shadows-of-Fire** [comment]
version?

**Comment by AlignedCookie88** [comment]
Sorry for the late reply. My version is `1.18.2-4.1.2`.

**Comment by Shadows-of-Fire** [comment]
Fixed in 4.1.4
