### ISSUE TITLE
[Suggestion] Load resources from openloader

### ISSUE THREAD

**Issue by GoldenTotem** [Shadows-of-Fire/PackMenu#45]
Hello, I am using [openloader](https://www.curseforge.com/minecraft/mc-mods/open-loader) mod and packmenu mod for 1.16.5. I noticed that this mod could could resources from .minecraft/openloader/resources/packmenu folder if packmenu/ is not existed in .minecraft/ . But if I restart the game, .minecraft/packmenu/ folder will be regenerated that resources in openloader folder will not be loaded. Could you add a configuration to let the mod load resources from openloader?

**Comment by TreaBeardGaming** [comment]
@GoldenTotem Just a note from openloader mod page that specifically says it loads after base loads and to try using crafttweaker to script something specifically for your use case.

https://www.curseforge.com/minecraft/mc-mods/open-loader

> - How does pack load order work?
> - Any resource packs loaded by OpenLoader should be loaded after vanilla and modded resource packs. Data pack load orders are done on a per-world basis instead and can be very annoying. Initially all data packs loaded by this mod will be loaded after vanilla and modded packs. Any mods added to the game after that initial world load will load after all previously loaded packs but only for that world. This can be fixed by using Vanilla's data pack command to correct the world order on a per-world basis. If you need more consistent control over load order I would recommend a scripting tool like [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker) which is more robust and stable than the data pack system.

With that in mind... Craft Tweaker really is amazing

**Comment by GoldenTotem** [comment]
> @GoldenTotem Just a note from openloader mod page that specifically says it loads after base loads and to try using crafttweaker to script something specifically for your use case.
> 
> https://www.curseforge.com/minecraft/mc-mods/open-loader
> 
> > * How does pack load order work?
> > * Any resource packs loaded by OpenLoader should be loaded after vanilla and modded resource packs. Data pack load orders are done on a per-world basis instead and can be very annoying. Initially all data packs loaded by this mod will be loaded after vanilla and modded packs. Any mods added to the game after that initial world load will load after all previously loaded packs but only for that world. This can be fixed by using Vanilla's data pack command to correct the world order on a per-world basis. If you need more consistent control over load order I would recommend a scripting tool like [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker) which is more robust and stable than the data pack system.
> 
> With that in mind... Craft Tweaker really is amazing

I have read it but I don't understand. I means packmenu cannot use the resource files in openloader/ and it have no matter with loading order. I think it is likely the problem of packmenu.

**Comment by GoldenTotem** [comment]
I think folder packmenu/ has higher priority than openloader/. So if packmenu/ is existed, files in openloader/ will be ignored. I want packmenu/ will not be generated so that files in openloader/ will always be used (and there can be less folders in .minecraft)

**Comment by Shadows-of-Fire** [comment]
The folder will not be regenerated as long as it exists.  You can just remove the files from the `assets` subdirectory of the packmenu folder and leave it empty.
