### ISSUE TITLE
Button Issues

### ISSUE THREAD

**Issue by CronaG** [Shadows-of-Fire/PackMenu#47]
Hello i use Packmenu 1.16.5-2.0.5 and i have a bug, none of the buttons are displayed.
Do you know where this could come from ?

![image](https://github.com/Shadows-of-Fire/PackMenu/assets/57565894/355398bc-c860-468d-bedf-0183f8ec37d3)

**here is the list of my mods :**

"E:\new modpack\mods\_MixinBootstrap-1.1.0.jar"
"E:\new modpack\mods\alexsmobs-1.12.1.jar"
"E:\new modpack\mods\ApocalypseNow_1.16.5_v1.10.jar"
"E:\new modpack\mods\appliedenergistics2-8.4.7.jar"
"E:\new modpack\mods\architectury-1.32.68.jar"
"E:\new modpack\mods\armourersworkshop-forge-1.16.5-2.0.6.jar"
"E:\new modpack\mods\ars_nouveau-1.16.5-1.25.10.jar"
"E:\new modpack\mods\AttributeFix-1.16.5-10.1.4.jar"
"E:\new modpack\mods\awesomedungeonend-forge-1.16.5-3.1.1.jar"
"E:\new modpack\mods\awesomedungeon-forge-1.16.5-3.2.0.jar"
"E:\new modpack\mods\awesomedungeonnether-forge-1.16.5-3.1.1.jar"
"E:\new modpack\mods\baubleyheartcanisters-1.16.5-1.1.11.jar"
"E:\new modpack\mods\BedBenefits-1.16.5-5.0.5.jar"
"E:\new modpack\mods\betterendforge-1.16.5-1.6.3.jar"
"E:\new modpack\mods\bettervillage-forge-1.16.5-3.2.0.jar"
"E:\new modpack\mods\Bloxys-Structures-1-14.jar"
"E:\new modpack\mods\Bookshelf-Forge-1.16.5-10.4.33.jar"
"E:\new modpack\mods\Botania-1.16.5-420.3.jar"
"E:\new modpack\mods\BrassAmberBattleTowers-1.16.5-1.6.3.jar"
"E:\new modpack\mods\byg-1.3.6.jar"
"E:\new modpack\mods\citadel-1.8.1-1.16.5.jar"
"E:\new modpack\mods\ClientTweaks_1.16.3-5.3.0.jar"
"E:\new modpack\mods\cloth-config-4.17.101-forge.jar"
"E:\new modpack\mods\collective-1.16.5-5.49.jar"
"E:\new modpack\mods\configured-1.5.4-1.16.5.jar"
"E:\new modpack\mods\Controlling-7.0.0.29.jar"
"E:\new modpack\mods\CosmeticArmorReworked-1.16.5-v5.jar"
"E:\new modpack\mods\CraftTweaker-1.16.5-7.1.2.521.jar"
"E:\new modpack\mods\CreativeCore_v2.2.1_mc1.16.5.jar"
"E:\new modpack\mods\CTM-MC1.16.1-1.1.2.6.jar"
"E:\new modpack\mods\Cucumber-1.16.5-4.1.12.jar"
"E:\new modpack\mods\curios-forge-1.16.5-4.1.0.0.jar"
"E:\new modpack\mods\CustomNPCs-1.16.5.20220515.jar"
"E:\new modpack\mods\CustomWindowTitle-1.15+v1.1.1.jar"
"E:\new modpack\mods\deuf-1.16.5-1.1.jar"
"E:\new modpack\mods\DungeonCrawl-1.16.5-2.3.12.jar"
"E:\new modpack\mods\dungeons_1.10.3_mc1.16.5.jar"
"E:\new modpack\mods\eidolon-0.2.7.jar"
"E:\new modpack\mods\elevatorid-1.16.5-1.7.13.jar"
"E:\new modpack\mods\EndReborn+[0.8.4].jar"
"E:\new modpack\mods\enhancedcelestials-2.0.9-1.16.5.jar"
"E:\new modpack\mods\EnigmaticLegacy-2.11.12.jar"
"E:\new modpack\mods\ExtendedCrafting-1.16.5-3.1.13.jar"
"E:\new modpack\mods\FpsReducer-forge-1.24-mc1.16.5.jar"
"E:\new modpack\mods\ftb-chunks-forge-1605.3.4-build.220.jar"
"E:\new modpack\mods\ftb-essentials-1605.1.5-build.32.jar"
"E:\new modpack\mods\ftb-library-forge-1605.3.4-build.90.jar"
"E:\new modpack\mods\ftb-teams-forge-1605.2.3-build.40.jar"
"E:\new modpack\mods\ftb-ultimine-forge-1605.3.1-build.45.jar"
"E:\new modpack\mods\geckolib-forge-1.16.5-3.0.106.jar"
"E:\new modpack\mods\Gobber2-Forge-1.16.5-2.3.55.jar"
"E:\new modpack\mods\goblintraders-1.7.3-1.16.5.jar"
"E:\new modpack\mods\gravestone-1.16.5-1.0.6.jar"
"E:\new modpack\mods\heath+key.jar"
"E:\new modpack\mods\iceandfire-2.1.12-1.16.5-patch-1.jar"
"E:\new modpack\mods\invtweaks-1.16.4-1.0.1.jar"
"E:\new modpack\mods\item-filters-forge-1605.2.5-build.9.jar"
"E:\new modpack\mods\Jade-1.16.4-2.8.3.jar"
"E:\new modpack\mods\jei-1.16.5-7.8.0.1009.jar"
"E:\new modpack\mods\jeiintegration_1.16.5-7.1.0.22.jar"
"E:\new modpack\mods\JEITweaker-1.16.5-1.1.0.49.jar"
"E:\new modpack\mods\JustEnoughResources-1.16.5-0.12.2.216.jar"
"E:\new modpack\mods\justplayerheads_1.16.5-2.0.jar"
"E:\new modpack\mods\libraryferret-forge-1.16.5-4.0.0.jar"
"E:\new modpack\mods\lootbeams-1.16.5-release-july1722.jar"
"E:\new modpack\mods\lycanitesmobs-1.16.5-2.3.3.3.jar"
"E:\new modpack\mods\Mantle-1.16.5-1.6.157.jar"
"E:\new modpack\mods\Mekanism-1.16.5-10.1.2.457.jar"
"E:\new modpack\mods\minecraft-comes-alive-7.3.23+1.16.5-universal.jar"
"E:\new modpack\mods\mining_dimension-1.16.5-1.0.6.jar"
"E:\new modpack\mods\MorePlayerModels-1.16.5.20220731.jar"
"E:\new modpack\mods\MouseTweaks-2.14-mc1.16.2.jar"
"E:\new modpack\mods\mowziesmobs-1.5.27.jar"
"E:\new modpack\mods\MutantBeasts-1.16.4-1.1.3.jar"
"E:\new modpack\mods\mutantmore-1.16.5-1.0.2.jar"
"E:\new modpack\mods\MysticalAgradditions-1.16.5-4.2.4.jar"
"E:\new modpack\mods\MysticalAgriculture-1.16.5-4.2.6.jar"
"E:\new modpack\mods\mysticalworld-1.16.5-0.3.6.27.jar"
"E:\new modpack\mods\Netherite Spawn+.jar"
"E:\new modpack\mods\nutritionalbalance-1.16.5-0.7.14.jar"
"E:\new modpack\mods\PackMenu-1.16.5-2.5.0.jar"
"E:\new modpack\mods\Paraglider-1.16.5-1.3.2.14.jar"
"E:\new modpack\mods\ParCool-1.16.5-3.1.0.3-R.jar"
"E:\new modpack\mods\Patchouli-1.16.4-53.3.jar"
"E:\new modpack\mods\Placebo-1.16.5-4.7.1.jar"
"E:\new modpack\mods\pmmobridge-1.16.5-1.1.0.jar"
"E:\new modpack\mods\prefab-1.6.5.16.jar"
"E:\new modpack\mods\Project_MMO-1.16.5-3.69.0.jar"
"E:\new modpack\mods\Psi-1.16-97.474.jar"
"E:\new modpack\mods\rare-ice-0.2.2.jar"
"E:\new modpack\mods\realmrpg_dragon_wyrms_0.0.1_forge_1.16.5.jar"
"E:\new modpack\mods\simple-rpc-1.16.5-3.2.2.jar"
"E:\new modpack\mods\simpleshops-1.1.3.jar"
"E:\new modpack\mods\sons-of-sins-1.16.5-1.0.9.jar"
"E:\new modpack\mods\spiderstpo-1.16.4-2.0.0.jar"
"E:\new modpack\mods\StorageDrawers-1.16.3-8.5.2.jar"
"E:\new modpack\mods\The_Undead_End_1.16.5.jar"
"E:\new modpack\mods\theoneprobe-1.16-3.1.7.jar"
"E:\new modpack\mods\towers_of_the_wild-1.16.4-2.0.1.jar"
"E:\new modpack\mods\twilightforest-1.16.5-4.0.870-universal.jar"
"E:\new modpack\mods\worldedit-forge-mc1.16.3-7.2.2-dist.jar"
"E:\new modpack\mods\xlpackets-1.16.4-1.2.jar"

**Comment by TreaBeardGaming** [comment]
Launch minecraft with just packmenu and plecebo, do the buttons work?
If the buttons still don't work with just those two mods, then you did something wrong with the config files.

https://github.com/Shadows-of-Fire/PackMenu/wiki/PackMenu-Button-Schema
