### ISSUE TITLE
PackMenu is suppressing any KubeJS startup errors

### ISSUE THREAD

**Issue by pietro-lopes** [Shadows-of-Fire/PackMenu#48]
This is 1.20.1, Forge 47.1.3

PackMenu is suppressing this screen <https://github1s.com/KubeJS-Mods/KubeJS/blob/2002/common/src/main/java/dev/latvian/mods/kubejs/client/KubeJSErrorScreen.java> that is set here <https://github1s.com/KubeJS-Mods/KubeJS/blob/2002/common/src/main/java/dev/latvian/mods/kubejs/client/KubeJSClientEventHandler.java#L154-L155>

Currently we need to disable this screen and use the older one to show something.

**Comment by Shadows-of-Fire** [comment]
PackMenu makes no attempt to prevent other screens from showing, it uses a normal priority event handler to replace the title screen: https://github.com/Shadows-of-Fire/PackMenu/blob/1.18/src/main/java/shadows/packmenu/PackMenuClient.java#L145
It seems like KJS should be using a lower priority handler to show the error screen.

**Comment by pietro-lopes** [comment]
Thanks! I will report to KJS Team.
