### ISSUE TITLE
Slideshow format

### ISSUE THREAD

**Issue by Jerma366** [Shadows-of-Fire/PackMenu#49]
How do I make the slideshow?

**Comment by BichoMESP** [comment]
slideshow {
    # The list of textures to be displayed on the slideshow.  If empty, the slideshow is ignored.
    # Default: [
    S:Textures <
	packmenu:textures/background/fondo1.png
	packmenu:textures/background/fondo2.png
	packmenu:textures/background/fondo3.png
	packmenu:textures/background/fondo4.png
     >
