### ISSUE TITLE
[1.14.4] Button Issues

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/PackMenu#5]
The 1.14.4 version of PackMenu seems to have an issue with text alignment on buttons, and small buttons get a weird `-` and `...` on top. The exact* same config and resource pack works without issues on 1.15.2

![billede](https://user-images.githubusercontent.com/21295394/76255157-04757880-624e-11ea-9f9d-ba6ba68d4eef.png)

### Version
- PackMenu-1.14.4-0.2.1

[Resources](https://github.com/NillerMedDild/Enigmatica4/tree/develop/openloader/resources/enigmatica/assets/enigmatica)
[Config](https://github.com/NillerMedDild/Enigmatica4/blob/develop/config/packmenu.cfg)

*Not exact same resourcepack, the logo has a 4 instead of 5 in it.*

**Comment by Shadows-of-Fire** [comment]
Ah, yeah, the 1.14 version needs the current changes backported, it only has the changes as of 1.2.1, not the current as of 1.2.4

**Comment by Shadows-of-Fire** [comment]
Closed by 1653a8a

**Comment by NielsPilgaard** [comment]
Thanks a lot :)

**Comment by NielsPilgaard** [comment]
The issue is not fixed in `PackMenu-1.14.4-0.2.4` I'm afraid.

**Comment by NielsPilgaard** [comment]
The issue is fixed, Shadows explained on Discord that the button is some other mod setting the lang key "" to something. Adding `"": ""` to a lang file in openloader fixed it.
Text alignment was fixed in `1.14.4-0.2.4`
