### ISSUE TITLE
[Suggestion] Image scaling based on size of window/gui scale level

### ISSUE THREAD

**Issue by BBoldt** [Shadows-of-Fire/PackMenu#7]
I'm currently using PackMenu to create a cool main menu for my modpack, and running into some issues which i'm not sure how to solve.

So, I am using a custom image for the title, which looks great if I have the window maximized:
![](https://i.imgur.com/IGejcts.jpg)

But if I try to resize the window it does this:
![](https://i.imgur.com/Fin0MLw.png)

Is there a way to avoid this already that I'm missing?

**Comment by Shadows-of-Fire** [comment]
Are you using the Logo feature in the config or overriding the existing title image?  The logo should be scaled like buttons

**Comment by BBoldt** [comment]
I am using the logo feature.

Config:
https://slexy.org/view/s20MNhiGJl

**Comment by Shadows-of-Fire** [comment]
I want to say it's because your actual png is a square with a ton of empty space that it's getting scaled the way it is, but this stuff is really particular in how it does everything.

Alternatively you could try replacing the vanilla title png, and see how well it places that where it needs to be.

**Comment by Shadows-of-Fire** [comment]
Additionally, if you want it to move around with the buttons, you should try to use the same anchor point as the buttons as much as possible (`DEFAULT` or `DEFAULT_LOGO`, both have the same literal positions, just the button has an additional +48 Y offset)

**Comment by BBoldt** [comment]
I ended up just mapping all the buttons to BOTTOM_CENTER to avoid issues. Thanks for your help!

![](https://i.imgur.com/aPVdvj0.jpg)

![](https://i.imgur.com/qIpb6eD.png)

(menu still WIP)
