### ISSUE TITLE
Anchor Point's don't work

### ISSUE THREAD

**Issue by kreezxil** [Shadows-of-Fire/PackMenu#8]
The new anchor points, when I add them, the button no longer renders on the screen, if I take the anchor tag out, and go back to configuring from the center they reappear.

In the following I would expect the accessibility button to be in the upper left which is "TOP_LEFT", w/e that coord maybe and that my "x" and "y" parameters are treated as offsets to that coordinate.

```json
{
	"x": 40,
	"y": 40,
	"width": 20,
	"height": 20,
	"u": 0,
	"v": 0,
	"hoverU": 0,
	"hoverV": 20,
	"texWidth": 32,
	"texHeight": 64,
	"texture": "textures/gui/accessibility.png",
	"action": "OPEN_GUI",
	"data": "ACCESSIBILITY",
	"anchor": "TOP_LEFT"
}
```

**Comment by kreezxil** [comment]
nevermind, i'm not paying attention to what I'm doing on this end.

**Comment by JAcamp1** [comment]
What is the issue with this and how did you resolve it?
