### ISSUE TITLE
[feature] have buttons with animated/scrolling text

### ISSUE THREAD

**Issue by kreezxil** [Shadows-of-Fire/PackMenu#9]
I know this might hard to implement or one of those "no i won't do that" but I think it would open a world of possibilities if we could have buttons that support scrolling of text when the text that goes on the button will exceed the button size.

either automatically or via another json boolean to activate it.

**Comment by Shadows-of-Fire** [comment]
Something I would like to do but low on the priority list right now.

**Comment by Shadows-of-Fire** [comment]
Implemented as of PM 2.4 https://streamable.com/kqm0xf
